fate#324198: updated description and proposal
yast/system-role-minimal-desktop pull request #1
Opened 2018-01-24 15:44 UTC by fcrozat

2018-01-25 08:37 UTC, gilsonsouza requested changes
Just the version should be according to our system.

2018-01-25 08:37 UTC, gilsonsouza commented on package/system-role-minimal-desktop.changes
> +- 16.0.0
Our version system: SLE_version.service_pack.changes
So it would be 15.0.1

2018-01-25 08:37 UTC, gilsonsouza commented on package/system-role-minimal-desktop.spec
> +Version:        16.0.0
Same as mentioned above.

2018-01-26 10:49 UTC, jreidinger approved these changes

2018-01-26 14:53 UTC, gilsonsouza approved these changes

2018-01-26 15:16 UTC, merged